spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost/askfood?createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
    jackson:
        deserialization:
            fail-on-ignored-properties: true
            fail-on-unknown-properties: true
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57Dialect
                format_sql: true
        show-sql: true
    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false
