spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost/askfood?createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57Dialect
        show-sql: true
